version: "3.9"
services:
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    env_file:
      - backend/.env
    tty: true
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000

  frontend:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: '/app'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - 5173:5173
